INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Pulse', 'Pulse', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Blood Pressure', 'BP', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Respiratory rate', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Temperature', 'Temp', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Nutritional status ', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Speech', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Cranial nerves ', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Pupil rt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Fundus', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Nystagmus ', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Motor function', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Fasciculation', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Involuntary movement', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Hemiparesis rt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Monoparesis rt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Monoparesis lt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Paraplegia', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Weakness of ', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R biceps rt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R biceps lt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R triceps rt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R triceps lt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R supinator rt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R supinator lt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R knee rt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R knee lt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R ankle rt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R ankle lt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R plantar rt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('R plantar lt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Gait ', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Heel Waking', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Toe Waking', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Cerebellar function', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Ataxia present in ', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Sensory function', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Spinal segment', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Neck rigidity', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Kernig s sign ', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Spinal deformity', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Spinal tenderness', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Pupil lt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Hemiparesis lt', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Blood Group', 'Blood Gp', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Position', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Body Build', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Dispnoea', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Anaemia', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Cyanosin', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Jaundice', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Clubbing', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Koilonychid', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Oedema', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Dehydration', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('JVP', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Lymph Adinopatly', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('skin Color', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Thyroid Gland', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Shape of Chest', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Deformity', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Movement', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Position of Trachae', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Expension', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Psycurion', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Breath Saund', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Addid Sound', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Vocal Resonanc', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Heart Sound S1', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Heart Sound S2', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Heart Sound S3/S4', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Heart Sound Murmur', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('HS Pericurial Rub', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('liver', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Ascirtes', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Kidneys', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Nervous System', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Locomotor System', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Others', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Animea', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Weight', 'Wt', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Height', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Heart', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Lungs', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Thyroid', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Breast', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Skin', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Abdomen ', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Umbilicus', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Lump size', 'Size', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Lump Shape', 'Shape', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Lump mobility', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Lump tender', 'Tender', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Ascitis', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Vulva', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('P/S', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Cervix', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Uterus', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Uterus Size', 'Size', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Uterus Position', 'Position', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Uterus Mobility', 'Mobility', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Fornix', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('S1', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('S2', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Murmer', '', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('BMI', 'BMI', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('BP', 'BP', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Planter', 'Planter', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Muscle power', 'Muscle power', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('S.L.R', 'S.L.R', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Tremor', 'Tremor', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Knee joint', 'Knee joint', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Neckvein', 'Neckvein', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Nose', 'Nose', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Trachea', 'Trachea', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Breath sound', 'Breath sound', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('NAD', 'NAD', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('CVS', 'CVS', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Liver', 'Liver', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Spleen', 'Spleen', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Cervical LN Rt', 'Cervical LN Rt', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Cervical LN Lt', 'Cervical LN Lt', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Supraclavicular LN Rt', 'Supraclavicular LN Rt', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Supraclavicular LN Lt', 'Supraclavicular LN Lt', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Tonsils', 'Tonsils', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Heart', 'Heart', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Sputum', 'Sputum', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('LMP', 'LMP', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('ALC', 'ALC', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('LC', 'LC', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('GB', 'GB', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('G', 'G', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('P', 'P', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('EDD', 'EDD', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MF', 'MF', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Para', 'Para', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Flow', 'Flow', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Higher psychic funct', 'Higher psychic funct', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Speech', 'Speech', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Cranial nerves', 'Cranial nerves', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Fundus', 'Fundus', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Nystagmus', 'Nystagmus', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Planter', 'Planter', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Muscle power', 'Muscle power', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Gait', 'Gait', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Cerebellar function', 'Cerebellar function', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Neck rigidity', 'Neck rigidity', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('S.L.R', 'S.L.R', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Tremor', 'Tremor', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Nervous System', 'Nervous System', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Knee joint', 'Knee joint', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Motor function', 'Motor function', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Hight', 'Hight', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Expected Body Weight', 'Expected Body Weight', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('M P Height', 'M P Height', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('TV', 'TV', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('SPL', 'SPL', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Acanthosis Nigrican', 'Acanthosis Nigrican', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Male Pattern Facial Hair', 'Male Pattern Facial Hair', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Exopthalmos', 'Exopthalmos', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('HbA1C (%)', 'HbA1C (%)', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Over Weight', 'Over Weight', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('e GFR equals to  (ml/min/1.73m)', 'e GFR equals to  (ml/min/1.73m)', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('BPB', 'BPB', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_vital (vitalName, shortName, vitalUnit, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MPH £.CM', 'MPH £.CM', 'undefined', 'system', NOW(), 'system', NOW());