INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (1, 'O+v', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (1, 'O-v', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (2, 'Married', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (2, ' Divorced', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (2, ' Single', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (11, '1', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (11, '2', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (11, '3', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (12, '1', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (12, '2', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (12, '3', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (18, 'A', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (18, 'B', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (18, 'C', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (21, 'Yes', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (21, 'No', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (26, 'Yes', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (43, 'Irragular', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (30, 'NAD', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (30, 'Disterded', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (30, 'Palpable Lemp', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (30, 'Mobility', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (30, 'Tenderness', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (30, 'Rigidity', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (30, 'Ascites', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (31, 'Uterus', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (31, 'Position', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (31, 'Mobility', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (31, 'Fornices', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (48, 'Slight Spotting', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (49, 'Regular', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (49, 'Irregular', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (35, 'Present', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (35, ' Absent', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (39, 'Present', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history_option (historyID, optionName, updatedBy, updatedOn, createdBy, createdOn) VALUES (39, 'Absent', 'system', NOW(), 'system', NOW());