INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Genric', '', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('NIPRO JMI', 'jmi', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('SQUARE', 'square', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Incepta', 'incepta', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Skf', 'skf', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Beximco', 'beximco', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Acme', 'acme', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Opsorin', 'opsotin', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('ACI', 'aci', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Globe', 'globe', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Aristo Pharma', 'aristo', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('General Pharma', 'general', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('healthcare', 'healthcare', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Renata', 'Renata', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Unimed', 'Unimed', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Radiant', 'rad', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Novartis', 'nov', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Drug Int', 'drug int', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Navana', 'navana', 'system', NOW(), 'system', NOW());