INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Blood Group', 'B.G', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Marital Status', 'Marital Status', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'MP', 'MP', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'MC', 'MC', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Cervical Smear', 'Cervical Smear', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'LMP', 'LMP', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'EDD', 'EDD', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'EDD By USG', 'EDD By USG', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'test', 'test', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'test2', 'test2', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('OBS', 'Para', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('OBS', 'Gravida', 'Gravida', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('OBS', 'Test', 'Test', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('OBS', 'Lucs', 'Lucs', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('OBS', 'ttttttt', 'ttttttt', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('OBS', 'hghfg', 'hghfg', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('OBS', 'undefined', 'undefined', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Frog', 'Frog', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Heart', 'level', 'level', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Post coital bleeding', 'Post coital bleeding', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('RISK', 'Smoking', 'Smoking', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('RISK', 'Test', 'Test', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('ALLERGY', 'Dust', 'Dust', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('OBS', 'EDD', 'EDD', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Para', 'Para', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Gravida', 'Gravida', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'P/A', 'P/A', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'P/V', 'P/V', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Appearance', 'Appearance', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Co Operation', 'Co Operation', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Decubitus', 'Decubitus', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Anaemia', 'Anaemia', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Jaundice', 'Jaundice', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Dehydration', 'Dehydration', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Cyanosis', 'Cyanosis', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Oedema', 'Oedema', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Leuconykia', 'Leuconykia', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Koilonykia', 'Koilonykia', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'MF', 'MF', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Cycle', 'Cycle', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'MP/MC', 'MP/MC', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Married', 'Married', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Para', 'Para', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Contraceptive H', 'Contraceptive H', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Bleeding', 'Bleeding', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Menstruation', 'Menstruation', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Scar', 'Scar', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'Menopausal', 'Menopausal', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'A/V', 'A/V', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.history (typeCode, name, shortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('MH', 'DM', 'DM', 'system', NOW(), 'system', NOW());