INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Medicine', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Cardiologist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Gastrologist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Neurologist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('ENT Specilist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Chest Specialist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Pediatrician', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Gynecologist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Onchologist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Eye Specialist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Diabetologist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Dermatologist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Orthopedics', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Nephrologists', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Infectious Disease Specialist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Psychiatrist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Endocrinologist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Gastroenterologist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Ophthalmologist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Otolaryngologists', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Podiatrist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Pulmonologists', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Rheumatologist', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Surgeon', 'system', NOW(), 'system', NOW());
INSERT IGNORE  INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Skin Specialist', 'system', NOW(), 'system', NOW());