INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('', '', '', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('আহারের পরে', 'After Meal', 'Avnv‡ii c‡i', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('খাবার আধা ঘণ্টা পূর্বে', '30 Minutes Before Meal', 'Lvevi Avav NÈv c~‡e©', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('আহারের আগে', '', 'Avnv‡ii Av‡M', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('ঘুমানোর পুর্বে', 'Before Sleep', 'Nygv‡bvi cy‡e©', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('ঘুম থেকে উঠে', 'After Wake-up', 'Nyg †_‡K D‡V', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('প্রয়োজন মত', 'SOS', 'cÖ‡qvRb g‡Zv', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('মাংস পেশীতে', 'IM', 'gvsm †ckx‡Z', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('শিরাতে', 'IV', 'wkiv‡Z', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('যোনিপথে', 'Pervaginal', '†hvwb c‡_', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('পায়ুপথে', 'Perrectum', 'cvqy c‡_', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('সকালে', '', 'mKv‡j', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('দুপুরে', '', '`ycy‡i', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('রাতে', '', 'iv‡Z', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('জ্বর না কমলে', '', 'R¡i bv Kg‡j', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('সন্ধ্যা বেলা আধা গ্লাস পানিতে গুলে খাবে', '', 'mÜ¨v †ejv Avav M­vm cvwb‡Z ¸‡j Lv‡e', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('প্রতি রাতে একই সময়', '', 'cÖwZ iv‡Z GKB mgq', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('সকালে ও দুপুরে', '', 'mKv‡j I `ycy‡i', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('সকালে ও রাতে', '', 'mKv‡j I iv‡Z', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('রাতের আহারের আধা ঘন্টা আগে', '', 'iv‡Zi Avnv‡ii Avav N›Uv Av‡M', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('আধা গ্লাস জলে গুলে খাবেন', '', 'Avav M­vm R‡j ¸‡j Lv‡eb', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('নাস্তার এক ঘণ্টা আগে', '', 'bv¯—vi GK NÈv Av‡M', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('আহারের ঠিক আগে', '', 'Avnv‡ii wVK Av‡M', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('মাসিকের ১-৫ দিন', '', 'gvwm‡Ki 1-5 w`b', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('শিরায়-বছরে ১টি', '', 'wkivq-eQ‡i 1wU', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('জ্বর থাকলে খাবেন।', '', 'R¡i _vK‡j Lv‡eb|', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('২ চামচ করে ৩ বার খাবেন।', '', '2 PvgP K‡i 3 evi Lv‡eb|', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('১ টি ট্যাবলেট-প্রতি সপ্তাহে', '', '', null, null, null, null);
INSERT INTO doctor_feed.content_when_type (bangla, english, pdf, updatedBy, updatedOn, createdBy, createdOn) VALUES ('রাতে আহারের পরে', '', '', null, null, null, null);