INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Medicine', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Cardiologist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Gastrologist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Neurologist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('ENT Specilist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Chest Specialist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Pediatrician', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Gynecologist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Onchologist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Eye Specialist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Diabetologist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Dermatologist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Orthopedics', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Nephrologists', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Infectious Disease Specialist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Psychiatrist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Endocrinologist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Gastroenterologist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Ophthalmologist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Otolaryngologists', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Podiatrist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Pulmonologists', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Rheumatologist', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Surgeon', null, null, null, null);
INSERT INTO doctor_feed.content_doctor_category (categortName, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Skin Specialist', null, null, null, null);