INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Genric', '', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('NIPRO JMI', 'jmi', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('SQUARE', 'square', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Incepta', 'incepta', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Skf', 'skf', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Beximco', 'beximco', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Acme', 'acme', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Opsorin', 'opsotin', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('ACI', 'aci', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Globe', 'globe', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Aristo Pharma', 'aristo', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('General Pharma', 'general', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('healthcare', 'healthcare', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Renata', 'Renata', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Unimed', 'Unimed', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Radiant', 'rad', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Novartis', 'nov', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Drug Int', 'drug int', null, null, null, null);
INSERT INTO doctor_feed.content_drug_company (companyName, folder, updatedBy, updatedOn, createdBy, createdOn) VALUES ('Navana', 'navana', null, null, null, null);